# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: backend-workflow

on:
  push:
    branches:
      - 'main'
      - 'backend'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        pm2 restart
