# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Frontend-workflow

on:
  push:
    branches:
      - 'main'
      - 'devops'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup working directory
        working-directory: ./backend
        run: ls -ll
      - name: run build command
        run: | 
            npm i -f 
            npm run build 
